import * as path from 'node:path';

import { describe, expect, it } from 'vitest';

import { renderPackageBin } from '../src/fsmPackage/bin.js';

describe('fsm package generated bin rendering', () => {
  it('renders the package runner shim with shebang, comment, import, argv, and exit handling', () => {
    const output = renderPackageBin({
      packageRoot: path.resolve('/repo/package'),
      binPath: path.resolve('/repo/package/bin/ah-example.mjs'),
    });

    expect(output.startsWith('#!/usr/bin/env node\n')).toBe(true);
    expect(output.split('\n')[1]).toBe(
      '// Generated by `aharness package build`; do not edit by hand.',
    );
    expect(output).toContain('import { runPackagedFsmCli } from "@aharness/core/package-runner";');
    expect(output).toContain('packageRootUrl: new URL("../", import.meta.url)');
    expect(output).toContain('argv: process.argv.slice(2)');
    expect(output).toContain('process.exit(exitCode);');
  });

  it('computes packageRootUrl for root and nested bin targets', () => {
    const rootBin = renderPackageBin({
      packageRoot: path.resolve('/repo/package'),
      binPath: path.resolve('/repo/package/ah-example.mjs'),
    });
    const nestedBin = renderPackageBin({
      packageRoot: path.resolve('/repo/package'),
      binPath: path.resolve('/repo/package/dist/bin/ah-example.mjs'),
    });

    expect(rootBin).toContain('packageRootUrl: new URL("./", import.meta.url)');
    expect(nestedBin).toContain('packageRootUrl: new URL("../../", import.meta.url)');
  });
});
