import * as path from 'node:path';

export interface RenderPackageBinOptions {
  readonly packageRoot: string;
  readonly binPath: string;
}

export function renderPackageBin(opts: RenderPackageBinOptions): string {
  const packageRootUrl = packageRootUrlFromBin({
    packageRoot: opts.packageRoot,
    binPath: opts.binPath,
  });

  return (
    '#!/usr/bin/env node\n' +
    '// Generated by `aharness package build`; do not edit by hand.\n' +
    'import { runPackagedFsmCli } from "@aharness/core/package-runner";\n' +
    '\n' +
    'const exitCode = await runPackagedFsmCli({\n' +
    `  packageRootUrl: new URL(${JSON.stringify(packageRootUrl)}, import.meta.url),\n` +
    '  argv: process.argv.slice(2),\n' +
    '  stdout: process.stdout,\n' +
    '  stderr: process.stderr\n' +
    '});\n' +
    '\n' +
    'process.exit(exitCode);\n'
  );
}

function packageRootUrlFromBin(opts: RenderPackageBinOptions): string {
  const packageRoot = path.resolve(opts.packageRoot);
  const binDir = path.dirname(path.resolve(opts.binPath));
  const relative = path.relative(binDir, packageRoot).replace(/\\/g, '/');
  if (relative === '') return './';
  return `${relative.endsWith('/') ? relative : `${relative}/`}`;
}
